name: Media3 FFmpeg Extension / Build

on:
  push:
    branches:
      - master
  pull_request:

env:
  NDK_VER: 21.4.7075529

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
        with:
          submodules: recursive
      - name: Setup Java
        uses: actions/setup-java@1df8dbefe2a8cbc99770194893dd902763bee34b # v3.9.0
        with:
          distribution: temurin
          java-version: 11
      - name: Setup Gradle
        uses: gradle/gradle-build-action@3fbe033aaae657f011f88f29be9e65ed26bd29ef # v2.3.3
      - name: Cache NDK
        uses: actions/cache@58c146cc91c5b9e778e71775dfe9bf1442ad9a12 # v3.2.3
        with:
          path: /usr/local/lib/android/sdk/ndk/${{ env.NDK_VER }}
          key: ${{ runner.os }}-${{ env.NDK_VER }}
      - name: Install correct NDK
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VER}"
      - name: Build ffmpeg
        run: ./build.sh
      - name: Build extension
        run: ./gradlew :media3-lib-decoder-ffmpeg:assembleRelease

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: "3.7"
      - uses: actions/checkout@v1
      - name: Fetch action
        id: pl
        uses: Rishabh510/Path-lister-action@master
        with:
        path: "media/"
        type: ".aar"
      - name: Output results
        run: |
          echo "Found ${{ steps.pl.outputs.path_count }} file(s) with this extension:"
          for i in ${{ steps.pl.outputs.paths }}; do
          echo $i
          done
      - name: upload result
        uses: actions/upload-artifact@v1
        with:
          name: media3-ffmpeg-extension
          path: ${MEDIA3_ROOT}/libraries/decoder_ffmpeg/buildout/outputs/aar/media3-lib-decoder-ffmpeg-release.aar
